# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c827d629eac25502598d621dba1e31e06b155566be5108e73122997c48fd6b61fed71e497db1f9ea213f809fdecf719e1b6f570d4a17619750dc13439d43655e

test:
  secret_key_base: 8c21cbb901ea3198112e6318bce78e5f7149794e402e09660d0f063e3dc578b321bb6f59574c8110ce673b9d8346ae1a10b03ef56ca20c08e3d2df39e561b695

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
